// @ts-check

/** 
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} 
 * 사이드바 설정 파일
 */
const sidebars = {
  mySidebar: [              
    {
      type: 'category',
      label: 'Gloria',
      link: {
        type: 'generated-index',
        title: 'GlORIA 구성 문서', // ✅ 자동 생성된 페이지의 제목
        //* description: 'This section covers all about network services.',
      },
      items: [{ type: 'autogenerated', dirName: 'gloria' }],
    },
    {
      type: 'category',
      label: 'Guide',
      link: {
        type: 'generated-index',
        title: '기술 문서', // ✅ 자동 생성된 페이지의 제목
        //* description: 'This section covers all about network services.',
      },
      items: [{ type: 'autogenerated', dirName: 'guide' }],
    },
],
 };



  // 설정 내보내기 (Docusaurus가 읽을 수 있도록 함)
  export default sidebars;
  